### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by GunnarFarneback** [GunnarFarneback/RegistryInstances.jl#2]
What should be part of the public API?

Proposal:
* `struct PkgInfo`
* `isyanked`
* `treehash`
* `compat_info`
* `struct PkgEntry`
* `registry_info`
* `struct RegistryInstance`
* `uuids_from_name`
* `reachable_registries`

Is something missing? Something that shouldn't be there?

**Comment by ericphanson** [comment]
when I was messing with trying an alternate resolver, this is what I was `using`:
```julia
using Pkg.Types: VersionRange, VersionSpec, read_project
using Pkg.Registry: registry_info, PkgEntry, compat_info
```
to try to build the compat graph of packages. I wanted to be able to be able to answer things like "what are all the versions of a package in the registry that are compatible with version X of another package?". PkgCompatUI's code was very helpful for that. So if you expose here whatever is needed for PkgCompatUI then that probably goes a long way.

**Comment by ericphanson** [comment]
@giordano and I might want to use this for PackageAnalyzer also, to not require the registry to be unpacked. For that I think then functionality you listed above is enough (don’t need `isyanked`, `treehash`, or `compat_info` though).

PkgDeps.jl would also probably be interested (cc @mattBrzezinski).
