### ISSUE TITLE
RegistryInstances.reachable_registries fails on nightly when called during package precompilation

### ISSUE THREAD

**Issue by j-fu** [GunnarFarneback/RegistryInstances.jl#8]
Here is an MWE (this is the way it it is used in Pluto where it occurs in https://github.com/fonsp/Pluto.jl/issues/2810)
```julia
module ttt
using RegistryInstances
_get_registries() = RegistryInstances.reachable_registries()
const _parsed_registries = Ref(_get_registries())
main() = _parsed_registries[]
end
```
When put into a file `ttt.jl` and included, it works well. 
When put into a directory on `LOAD_PATH` and invoked via `using ttt`, 
during the precompilation phase, on julia nightly one gets a similar error like in 
https://gist.github.com/j-fu/1fd2a044636cf0a2737b999db043cc22 : 
[uncompress_registry](https://github.com/GunnarFarneback/RegistryInstances.jl/blob/2796d959014475bc19e2dfa174179cdf02642d28/src/registry_instance.jl#L192) is able to read only the first three entries and then bails out with end of file. All is fine on 1.10.1.

I am on OpenSUSE Leap 15.5 on linux x86_64.

**Comment by j-fu** [comment]
May be this can be closed: it seems that `reachable_registries()` is 
better called during `__init__()`:

```julia
module ttt
using RegistryInstances
_get_registries() = RegistryInstances.reachable_registries()
const _parsed_registries = Ref(RegistryInstance[])
__init__()= _parsed_registries[] = _get_registries()
main() = _parsed_registries[]
end
```

See  https://github.com/fonsp/Pluto.jl/pull/2815

**Comment by GunnarFarneback** [comment]
I don't know what is different between 1.10 and nightly, but it does indeed seem questionable to have this information cached by precompilation. Especially considering that there are some tricks with lazy loading of package data.
